[profile.dev]
debug = true
panic = "abort"

[profile.dev.build-override]
incremental = false
opt-level = 0
rustflags = [
  "-Cembed-bitcode=no",
  "-Crelocation-model=pie",
  "-Cdebuginfo=2",
  "-Zmacro-backtrace",
]

[profile.release.build-override]
opt-level = 3

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
